version: '2'

### Creates a named network with the default bridge driver
# The network is shared between rcontainers
networks:
   magento-backend:

volumes:
    db-data:

services:
    sampleservice:
        image: webdevops/php-apache:7.3
        container_name: sample-service
        environment:
          - WEB_ALIAS_DOMAIN=http://robertod.germanywestcentral.cloudapp.azure.com/
          - WEB_DOCUMENT_ROOT=/sampleservice
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
        volumes:
          - ./sampleservice:/sampleservice
        ports:
          - "9000:80"
        networks:
          - magento-backend
    web:
        image: webdevops/php-apache:7.3
        container_name: magento-web
        user: application
        restart: always
        environment:
          - WEB_ALIAS_DOMAIN=http://robertod.germanywestcentral.cloudapp.azure.com/
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=-1
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500MB
          - PHP_UPLOAD_MAX_FILESIZE=1024MB
        volumes:
          - ./:/app:cached
          - ./:/magento
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
        networks:
          - magento-backend

    phpmyadmin:
        container_name: magento-phpmyadmin
        image: phpmyadmin/phpmyadmin:5.0.4
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
          - MYSQL_ROOT_PASSWORD=root
        ports:
          - "8081:80"
        depends_on:
          - mysql
        networks:
          - magento-backend

    mysql:
        image: mariadb:10.4
        container_name: magento-db
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        ports:
          - "3306:3306"
        networks:
          - magento-backend
        volumes:
          - db-data:/var/lib/mysql
        depends_on:
          - web

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        container_name: magento-elasticsearch
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          - "discovery.type=single-node"
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        networks:
          - magento-backend
        depends_on:
          - web
